// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: time/time.proto

package time

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuctionServiceClient is the client API for AuctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionServiceClient interface {
	Bid(ctx context.Context, in *BidMessage, opts ...grpc.CallOption) (*AuctionMessage, error)
	Result(ctx context.Context, in *AuctionItem, opts ...grpc.CallOption) (*AuctionInfo, error)
	CreateAuction(ctx context.Context, in *AuctionInfo, opts ...grpc.CallOption) (*AuctionMessage, error)
	GetAuctions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (AuctionService_GetAuctionsClient, error)
}

type auctionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionServiceClient(cc grpc.ClientConnInterface) AuctionServiceClient {
	return &auctionServiceClient{cc}
}

func (c *auctionServiceClient) Bid(ctx context.Context, in *BidMessage, opts ...grpc.CallOption) (*AuctionMessage, error) {
	out := new(AuctionMessage)
	err := c.cc.Invoke(ctx, "/time.auctionService/bid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) Result(ctx context.Context, in *AuctionItem, opts ...grpc.CallOption) (*AuctionInfo, error) {
	out := new(AuctionInfo)
	err := c.cc.Invoke(ctx, "/time.auctionService/result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) CreateAuction(ctx context.Context, in *AuctionInfo, opts ...grpc.CallOption) (*AuctionMessage, error) {
	out := new(AuctionMessage)
	err := c.cc.Invoke(ctx, "/time.auctionService/createAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) GetAuctions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (AuctionService_GetAuctionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AuctionService_ServiceDesc.Streams[0], "/time.auctionService/getAuctions", opts...)
	if err != nil {
		return nil, err
	}
	x := &auctionServiceGetAuctionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuctionService_GetAuctionsClient interface {
	Recv() (*AuctionInfo, error)
	grpc.ClientStream
}

type auctionServiceGetAuctionsClient struct {
	grpc.ClientStream
}

func (x *auctionServiceGetAuctionsClient) Recv() (*AuctionInfo, error) {
	m := new(AuctionInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuctionServiceServer is the server API for AuctionService service.
// All implementations must embed UnimplementedAuctionServiceServer
// for forward compatibility
type AuctionServiceServer interface {
	Bid(context.Context, *BidMessage) (*AuctionMessage, error)
	Result(context.Context, *AuctionItem) (*AuctionInfo, error)
	CreateAuction(context.Context, *AuctionInfo) (*AuctionMessage, error)
	GetAuctions(*Empty, AuctionService_GetAuctionsServer) error
	mustEmbedUnimplementedAuctionServiceServer()
}

// UnimplementedAuctionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuctionServiceServer struct {
}

func (UnimplementedAuctionServiceServer) Bid(context.Context, *BidMessage) (*AuctionMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (UnimplementedAuctionServiceServer) Result(context.Context, *AuctionItem) (*AuctionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedAuctionServiceServer) CreateAuction(context.Context, *AuctionInfo) (*AuctionMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuction not implemented")
}
func (UnimplementedAuctionServiceServer) GetAuctions(*Empty, AuctionService_GetAuctionsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAuctions not implemented")
}
func (UnimplementedAuctionServiceServer) mustEmbedUnimplementedAuctionServiceServer() {}

// UnsafeAuctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionServiceServer will
// result in compilation errors.
type UnsafeAuctionServiceServer interface {
	mustEmbedUnimplementedAuctionServiceServer()
}

func RegisterAuctionServiceServer(s grpc.ServiceRegistrar, srv AuctionServiceServer) {
	s.RegisterService(&AuctionService_ServiceDesc, srv)
}

func _AuctionService_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.auctionService/bid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).Bid(ctx, req.(*BidMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.auctionService/result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).Result(ctx, req.(*AuctionItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_CreateAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).CreateAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.auctionService/createAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).CreateAuction(ctx, req.(*AuctionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_GetAuctions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuctionServiceServer).GetAuctions(m, &auctionServiceGetAuctionsServer{stream})
}

type AuctionService_GetAuctionsServer interface {
	Send(*AuctionInfo) error
	grpc.ServerStream
}

type auctionServiceGetAuctionsServer struct {
	grpc.ServerStream
}

func (x *auctionServiceGetAuctionsServer) Send(m *AuctionInfo) error {
	return x.ServerStream.SendMsg(m)
}

// AuctionService_ServiceDesc is the grpc.ServiceDesc for AuctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "time.auctionService",
	HandlerType: (*AuctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "bid",
			Handler:    _AuctionService_Bid_Handler,
		},
		{
			MethodName: "result",
			Handler:    _AuctionService_Result_Handler,
		},
		{
			MethodName: "createAuction",
			Handler:    _AuctionService_CreateAuction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getAuctions",
			Handler:       _AuctionService_GetAuctions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "time/time.proto",
}
